name: tagged
description: A Newtype Pattern, a Safe & Type-Restricted Wrapper for Dart.
version: 0.1.0
homepage: https://github.com/minikin/tagged

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
